### PR TITLE
Add first steam steam-games version

### PR DESCRIPTION
**Pull request by 4n4n4s**
I did not yet add it to the autostart as some things still need to be refined. 
So please consider it as a draft/alpha version.

Maybe in the future we could use e.g. [steamdb.info](https://steamdb.info/instantsearch/?query=tile&refinementList%5Btags%5D%5B0%5D=Free%20to%20Play&refinementList%5Blanguages%5D%5B0%5D=English&refinementList%5BreleaseYear%5D%5B0%5D=2022&refinementList%5BreleaseYear%5D%5B1%5D=2023&range%5BuserScore%5D=80%3A&range%5Breviews%5D=200%3A&range%5Bfollowers%5D=200%3A&range%5Bprice_us%5D=%3A0) to get the games and only pick ones that have a certain rank etc or use some API. 
For now I guess it would be best to just maintain it manually.

### CODE REVIEW

**Comment by yoshimo** [comment]
Why steamDB where you would need api access and not the search parameters discussed in https://github.com/vogler/free-games-claimer/issues/89?

**Comment by 4n4n4s** [comment]
> Why steamDB where you would need api access and not the search parameters discussed in #89?

Do you mean https://store.steampowered.com/search/?sort_by=Reviews_DESC&as-hide=negative&maxprice=free&category1=998%2C21&specials=1&hidef2p=1&ndl=1?

**Comment by yoshimo** [comment]
Kind of yes. Not every parameter on the page can be set with url parameters but it would be a good start and then make the filters configurable that get send via POST in a second step.

**Comment by vogler** [comment]
Just wanted to check it out, but the commits are gone now.
Check `git reflog` if it was by accident.

**Comment by 4n4n4s** [comment]
I will bring it back but decided to remove it for now as I was not happy with the claiming url. I found a way how we can get giveaways using https://www.gamerpower.com/giveaways/steam/free-games

**Pull request closed without merging**
