### PR TITLE
fix restart issue

### PR DESCRIPTION
**Pull request by jumoog**
fix for #23 

now its possible to add a healthcheck and use tools like [deunhealth](https://github.com/qdm12/deunhealth/)

### CODE REVIEW

**Comment by vogler** [comment]
Thanks! I'm on vacation, I'll check it next weekend.

**Comment by vogler** [comment]
Can't test it now, but if it works for you, I can merge it.

**Comment by jumoog** [comment]
hmm maybe lets review from @jackblk

**Comment by jumoog** [comment]
I'll update this. I think the solution is the export of `DISPLAY`

**Comment by jackblk** [comment]
Haven't tested yet but LGTM 😄

**Review by jackblk — APPROVED** [review]

**Comment by vogler** [comment]
Just tried it. @jumoog is it no longer needed or why did you close it? Otherwise I'll merge.

**Comment by jumoog** [comment]
oh  sorry i was busy... thx for merge

**Pull request merged**
