### PR TITLE
epic-games: captcha on login: await notify

### PR DESCRIPTION
**Pull request by kevinmatthe**
Adding async handle in captcha notify

### CODE REVIEW

**Comment by kevinmatthe** [comment]
With this issue #191

**Comment by kevinmatthe** [comment]
@vogler I'm not familiar in front-end develop, so if there's any problem, please just directly point out~

**Comment by vogler** [comment]
Did you test if that fixes #191?
Adding async/await shouldn't make a difference here since the call to `notify` will be on the task queue either way.
(At least in theory, here's some nice visualization: https://dev.to/lydiahallie/javascript-visualized-promises-async-await-5gke)

**Comment by kevinmatthe** [comment]
> Did you test if that fixes #191? Adding async/await shouldn't make a difference here since the call to `notify` will be on the task queue either way. (At least in theory, here's some nice visualization: https://dev.to/lydiahallie/javascript-visualized-promises-async-await-5gke)

yes I tested this change and the console function before the notify function is correctly print to stdout.

**Comment by vogler** [comment]
Ok, maybe it makes some difference in how it's scheduled.

**Pull request merged**
