### PR TITLE
check if there are new games to claim before launching browser?

### LINKED ISSUE #29: check if there are new games to claim before launching browser?
## Feature

Why not determine if the promotion entity is already in the library before the claim-task is executed?

I think handling this pre-work before launching the browser would greatly improve workflow efficiency (If the identity token is cached).

## Description

Key: the namespace of a promotion is a unique value.

- [get_order_history (with cookies)](https://www.epicgames.com/account/v2/payment/ajaxGetOrderHistory?locale=en-US)
- [get_promotions](https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US)

Pseudo code
```python
def promotions_filter(self):
    # Get historical order data (10 items)
    order_history = self.explorer.game_manager.get_order_history(self._ctx_cookies)
    # Get weekly free game promotion data
    promotions = self.get_promotions()
    # Marks the in-library status of the promotion
    for promotion in promotions:
        # Check order.orderStatus == "COMPLETED" and promotion.namespace == order.namespace
        promotion.in_library = order_history.get(promotion.namespace, False)
        # Skip tasks that correspond to promotions already in the library
        self.task_queue_pending.put(promotion)
```

### PR DESCRIPTION
**Pull request by vogler**
Closes #29.

> I like the idea, but not sure yet if it's worth it.
> 
> Cons:
> 
> * extra code that can break and needs to be maintained
> * not starting the browser also means that cookies are not refreshed -> might have to re-login
> 
> Pros:
> 
> * if there's no new game to claim:
>   
>   * finish faster
>   * don't need to launch the browser which may be relevant for people who don't run it in docker

_Originally posted by @vogler in https://github.com/vogler/free-games-claimer/issues/29#issuecomment-1262786114_

> You can open a PR. It's not trivial to make it useful without adding lots of extra code.
> 
> 1. How do we refresh cookies if we don't open the browser? Seems like [get_order_history](https://www.epicgames.com/account/v2/payment/ajaxGetOrderHistory?locale=en-US) does not have the right `set-cookie:` response header, just noticed it setting `EPIC_CLIENT_SESSION` for `path=/account`.
> 2. How do we get the cookies without opening the browser?
>    
>    1. https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies - could save them into some file after every run that opened the browser.
>    2. https://playwright.dev/docs/api/class-browsercontext#browser-context-request - contains the cookies in the request, but needs a browser context, so we would first launch a headless browser to make the request and if there's something new we would need to re-launch non-headless to claim. Not great performance-wise.
> 
> What could be easily implemented is to check against the saved games in `data/epic-games.json`, but then you have problems if you start using multiple accounts. Could make the root keys the accounts though. However, how do you know the current account name without launching the browser?

_Originally posted by @vogler in https://github.com/vogler/free-games-claimer/issues/29#issuecomment-1263424294_

Options:
1. check order history using previously stored cookies
2. launch headless browser to check order history - should take care of handling cookies, but if there are games to claim we need to re-launch non-headless
3. ignore order history and check claimed games per account in data/epic-games.json

### CODE REVIEW

**Comment by vogler** [comment]
I tried option 1, but the required cookies are not stored from the previous browser session. Maybe you need to re-login or visit the account etc.

**Comment by QIN2DIM** [comment]
```yaml
{ 'domain': '.epicgames.com', 'expiry': 1667140387, 'httpOnly': True, 'name': 'EPIC_SSO_RM', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'ce34b5e4633d4005b03caeda607a1533' }
{ 'domain': '.epicgames.com', 'httpOnly': False, 'name': 'EPIC_LOCALE_COOKIE', 'path': '/', 'secure': False, 'value': 'zh-Hans' }
{ 'domain': '.epicgames.com', 'expiry': 1664577187, 'httpOnly': True, 'name': 'EPIC_SSO', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'ce34b5e4633d4005b03caeda607a1533' }
{ 'domain': '.epicgames.com', 'expiry': 1699108376, 'httpOnly': True, 'name': 'EPIC_DEVICE', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'f459bc0af0304c658bddf8e4af356f6c' }
{ 'domain': '.epicgames.com', 'expiry': 1696084380, 'httpOnly': False, 'name': '_tald', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'e6d741d1-e64a-4567-9fc0-9e32868d61dc' }
{ 'domain': '.epicgames.com', 'expiry': 1664577187, 'httpOnly': True, 'name': 'EPIC_BEARER_TOKEN', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': '078539b23ee441439f3da1f1c60ee585' }

```

**Comment by vogler** [comment]
Did it work for you with these cookies? Did you have to visit a certain page to get them set?

**Comment by vogler** [comment]
Closing this since the potential speedup is not worth the extra code and possible points of failure.

**Comment by weartist** [comment]
@vogler  Sorry to bother here, I'm working on an game inventory feature, but I've searched through Epic's API and haven't found out if they provide an account-owned game list API, it's possible that I didn't find it, so I'd like to trouble you, do you have an impression of this kind of API, thank you very much!

**Pull request closed without merging**
