### PR TITLE
fix: update epic claim confirmation text

### PR DESCRIPTION
**Pull request by luke-rie**
should fix: https://github.com/vogler/free-games-claimer/issues/125

### CODE REVIEW

**Comment by WiLuX-Source** [comment]
This can fix the issue for a while but iframe is no longer opened. Iframe checks are broken and that also needs to be fixed.

**Comment by vogler** [comment]
Can someone confirm that this change fixes it?
I think there are several strings - I've seen `Thanks for your order` before in the DOM while the script was checking for `Thank you for buying` and it was fine.

**Comment by vogler** [comment]
> This can fix the issue for a while but iframe is no longer opened. Iframe checks are broken and that also needs to be fixed.

What do you mean? The text is checked on `page`, not `iframe`. I don't see a change - the order still happens in `iframe`.

**Comment by WiLuX-Source** [comment]
> > This can fix the issue for a while but iframe is no longer opened. Iframe checks are broken and that also needs to be fixed.
> 
> What do you mean? The text is checked on `page`, not `iframe`. I don't see a change - the order still happens in `iframe`.

My bad. Yes it creates iframe again but after seeing changed reactmodal i mistaken it for the window. All fine.

I confirm that this pr fixes the current issue with validating if the game is picked or not.
image

**Pull request merged**
